name: crak-chess
version: 0.1.9.0
synopsis: A simple chess engine in haskell by Victaum
description: See README at <https://gitlab.com/victaum/vichess#readme>
maintainer: Victor H. Manotas G. <victorma32@gmail.com>
copyright:
  - (2020) Victor Hugo Manotas Garces
git: https://github.com/victaum1/crak_chess
license: MIT
extra-source-files:
  - doc/*
    #  - README.org
    #  - ChangeLog.org
category: Games

dependencies:
  - base >= 4.6 && < 5

library:
    source-dirs: src
    exposed-modules:
      - Board
      - Moves
      - Pieces
      - Squares
      - Game
      - Parsing
      - Generator
      - Valid
      - Play
      - Utils
      - Perft
      - Evaluate
      - Search
    dependencies:
      - containers

executables:
  crakchess-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      # - readline >= 1.0.3.0 && < 2
      - transformers
      - containers
      - random
      - clock

tests:
  u-perft:
    main: u-perft.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - HUnit
        # - containers

  u-moves:
    main: u-moves.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - HUnit
        # - containers

  u-game:
    main: u-game.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - HUnit
      - containers

  q-board:
    main: q-board.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - QuickCheck
      - containers

  q-squares:
    main: q-squares.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - QuickCheck

  u-squares:
    main: u-squares.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      - HUnit

  u-pieces:
    main: u-pieces.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      # - hspec
      # - mockery
      - HUnit
      # - build-tools: hspec-discover
 
  u-gen-sq-attack:
    main: u-gen-square_attack.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      #- template-haskell
      - HUnit
      - containers

  u-gen-pawn-move:
    main: u-gen-pawn_moves.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      #- template-haskell
      - HUnit
      - containers
  
  u-gen-qrbn-move:
    main: u-gen-qrbn_moves.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      #- template-haskell
      - HUnit
      - containers

  u-gen-king-move:
    main: u-gen-king_moves.hs
    source-dirs:
      - tests
    ghc-options:
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N
    dependencies:
      - crak-chess
      #- template-haskell
      - HUnit
      - containers

  u-play:
    main: u-play.hs
    source-dirs:
      - tests
    dependencies:
      - crak-chess
      - HUnit
        # - containers

