#+title: ReadMe of crak_chess
#+author: Victor H. Manotas G.
#+date: <2020-09-25 vie>  
* README

** Motivation
This project is a programming exercise where it is going to be implemented
a concrete case. The particular application is a simple chess engine. The
language to use is "Haskell", like a prototyping scheme.

** version 0.0.13.8
the versioning adopted will be the one like:
[[https://pvp.haskell.org/][The Haskell Versioning]]

** [[https://orgmode.org/#docs][Do you want to learn Org Mode?]]
** How to get setup?
*** Summary of set up:
We will be using the "ghc/ghci" compiler, or "Glascow Haskell Compiler".
Therefore it is recommended to download the "Haskell Platform". Will be
using "Cabal" as building tool.

*** Dependencies
The code will be based in the 8.6.5 version of "ghc".

*** How the tests will be made?
The unit tests will be made using the package "HUnit". Also, it will
be tests with "QuickCheck".

*** Deployment
The target will be to build a standalone binary. This one should be
communicating with some chess protocol (uci/xboard). That should work on
any machine. I will be versions for windows, MacOS and Linux.

** Who do I talk to?
With the repo owner or admin:
[[mailto:victorma31@gmail.com][Victaum]]
